version: "3.8"
services:
  web:
    image: simple-app:compose
    build: .
    ports:
      - "8000:8000"
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        order: start-first
      restart_policy:
        condition: on-failure
