name: CI
on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install linters
        run: pip install ruff flake8

      - name: Ruff check
        run: ruff check app

      - name: Flake8 check
        run: flake8 app

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - name: Build Docker image
        run: docker build -t simple-app:${{ github.sha }} .
